apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: db-credentials
  namespace: dsp-demo        # MUSS gleich Namespace-Ordner sein
spec:
  type: kv-v2
  mount: secret
  path: dsp/demo-app/database
  refreshAfter: 30s
  destination:
    name: db-credentials                 # Name des erzeugten K8s-Secrets
    create: true
  vaultAuthRef: default                  # Name des VaultAuth (aus Lab 01)
  # vaultAuthRef-Namespace siehe unten